# Generated by Django 3.2.6 on 2021-09-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_coinsubmit'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='ticker',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
