# Generated by Django 3.2.6 on 2021-09-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_coin_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricedynamic',
            name='cg_id',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
