# Generated by Django 3.2.6 on 2021-10-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_pricedynamic_cg_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='price_change24h',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
