# Generated by Django 3.2.6 on 2021-10-21 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_coin_price_change24h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change24h',
            field=models.FloatField(),
        ),
    ]
