# Generated by Django 3.2.6 on 2021-10-21 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_alter_coin_price_change24h'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='price_change24h',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
