# Generated by Django 3.2.6 on 2021-10-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_alter_coin_price_change24h'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='price_change24h',
        ),
        migrations.AddField(
            model_name='pricedynamic',
            name='price_change24h',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
