# Generated by Django 3.2.6 on 2021-11-14 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20211021_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricedynamic',
            name='price_change24h',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
