# Generated by Django 3.2.6 on 2022-02-07 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_pricedynamic_price_change24h'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='github',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
