# Generated by Django 3.2.6 on 2022-02-10 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='github',
            name='coin',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gh', to='news.coin'),
        ),
    ]
